var GAME_LEVELS = [
  ["                                                   vv                           ",
   "                                                                                ",
   "      @     o                                                                   ",
   "  xggxxxxxxxxxxxxx       xxxxxxxxxxxx                                           ",
   "                                    xx                                          ",
   "                 xxx                 xxooo    ooo     oo    ooo     o           ",
   "  xxxxxxxggxxxxxxxxxx                  xxx    xxxxx   xxxxxxxxxxxxxxxx          ",
   "              xxxxxxxxxxx                x!!!x   x!!!x                          ",
   "              xxxxxxxxxxxxxxx            xxxxx   xx!xx                          ",
   "     xggggggggxxxxxxxxxxxxxxxxx                    v                            ",
   "     x        xxxxxxxxxxxxxxxxxxxxx                                             ",
   "     x       xx   xxxxxxxx                                                      ",
   "     x        x   xxxxxxx     ooooooooooo                           o           ",
   "     x =      x     v   xxxxxxxxxxxxxxxxxx   xxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "     xggggggggx                     x    x   x                                  ",
   "     x                              x    x   x                                  ",
   "     x                    x         x    x   x                                  ",
   "     x                   xxxxxggggggx    x   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "     xxxxxxxxxxxxxxxxxxxxxx         x    x!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "     x        x           x         x    x!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "     x        x           x         x    x!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "     x        x                     x    x!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "     x        x =   w         xx  xxx    x!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "     x        xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["            |                                                                                                     ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "gggggggggxxxxxxxx xx    xxxx   xx   xxxxxx    xxxx xxxx   xx   xxxx   xxx    xxx   xxxxxxxx   xxxx                ",
   "            = x     !!!!    !!!  !!!      !!!!                                                                    ",
   "              x                                                                                        xxx        ",
   "       =      x                                                                                                   ",
   "              x                                                                                xxxxxx             ",
   "   =          x                                                                                                   ",
   "                                                                                     xxxxxxxx                     ",
   "    w                                                                                                             ",
   "                                                                           xxx                                    ",
   "                                                                                                                  ",
   "                                                                  xxx                                             ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "      @                                               ooo                    ooo                       ooo        ",
   "xxxxxxxxxxxxxxxx            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         xxxxxxxxxxxxxx",
   "               x                                                              v   v    v                          ",
   "               x                                                                             xxxxx                ",
   "               x                                                                                                  ",
   "               x=                                                                  ooo                 ooo        ",
   "               x                                                            xx xxx xxxx xxx        xxxxxxxxxx     ",
   "               x                                           x   ooo =   x                                          ",
   "               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxx                                          ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                               xxxxxxxxxxgggggggx             ",
   "                                                                                        x       x             ",
   "                                                                           xxxxx        x       x             ",
   "                                                                                        x=      x             ",
   "                                                                   xxxxxxxxx            xgggggggx             ",
   "                                                              xxx                       xgggggggx             ",
   "                                                        xxx                             x       x             ",
   "                                                  xxx                                   x   =   x             ",
   "                                            xxx                                         x=      x             ",
   "     @                                                                                  x       x             ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                               xgggggggx             ",
   "                 x                           o                                          x       x             ",
   "                 x                          xxx                                         x       x             ",
   "                 x                                               o                      x=      x             ",
   "xxxxxxxxxxxxxxxxxx                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!   !!xxxxxxxxxxxxxx",
   "   | |           x                                                                      x       x             ",
   "                 x                                                                      x   w   x             ",
   "                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  =xxx=        xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  ooo    =x      x               v       v                                                                    ",
   "xxxxxxxxxxxx     x                                                        xxx                                 ",
   "     |  |  xx    x                                       ooo                                      ooo         ",
   "               xxx             o      o            xxxxxxxxxxxxxxxxxxxxxx      xxx      xxxxxxxxxxxxxxxxxxxxxx",
   "             xxx               xxx    xxx                                                                     ",
   "o                          xxx!!!!!!!!!!!!!!xxxxxxxx                                                          ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                 xx                           ",
   "                                                                                xxxx                          ",
   "             x       x  xxxxxxx  xxxxxxx  xxxxxxx  xxxxxxx  xxxxxxx  x     x    xxxx                          ",
   "              x     x      x     x           x     x     x  x     x   x   x      xx                           ",
   "               x   x       x     x           x     x     x  xxxxxxx    x x                                    ",
   "                x x        x     x           x     x     x  x    x      x        xx                           ",
   "                 x      xxxxxxx  xxxxxxx     x     xxxxxxx  x     x     x        xx                           ",
   "                                                                                                              ",
   "   @                                                                                                          ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    x!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    x!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    x!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxx",
   "                                                                                              x               ",
   "                                                                                              x               ",
   "                                                                                              x               ",
   "                                                                                              x               ",
   "                                                                                              x               ",
   "                                                        xx     xx                             x               ",
   "                                                                                              x               ",
   "                             vxxx xxx xxx xxx xxx xxxv  xx     xx                             x               ",
   "                              x   x   x   x x x    x    xx     xx                             x               ",
   "                             vxxx xxx x   xxx xxx  x v     xxx                                x               ",
   "                                x x   x   xx  x    x      x!!!x                               x               ",
   "                             vxxx xxx xxx x x xxx  x v   x!!!!!x                              x               ",
   "                                                          xxxxx                               x               ",
   "                             v                       v                                        x               ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
